### ISSUE TITLE
Invite to make your repo CP_MATHS as part of CCDSAP Roadmap

### ISSUE THREAD

**Issue by adeepak7** [ashtnemi448/CP_MATHS#1]
Hi @ashtnemi448 - It seems that you are quite interested in cp maths and CCDSAP Roadmap needs your contribution from mathematical point of view.

How to contribute:

Name each file as the name of the concept of the code. For example, CheckIsPrime, Triangular Numbers etc.

Kindly add the link for the problem statement in the first line of solution file.

Checkout CCDSAP Roadmap at: https://github.com/adeepak7/CCDSAP-Roadmap

Thanks.

**Comment by ashtnemi448** [comment]
Sure!
Will do that.
